language: java
jdk:
  - openjdk7
  - oraclejdk7


sudo: required

services:
  - docker

install:
  - wget --no-check-certificate https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz
  - tar -xzvf protobuf-2.5.0.tar.gz
  - cd protobuf-2.5.0 && ./configure --prefix=/usr && make && sudo make install && cd -
  # Download desired version of Gradle
  - wget https://services.gradle.org/distributions/gradle-2.14-bin.zip
  - unzip -qq gradle-2.14-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.14
  - export PATH=$GRADLE_HOME/bin:$PATH

script:
  - gradle build
  - gradle check
  - gradle javadoc
  - gradle buildDocker

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push srangwal/griffin

